data_dir: "data\\battery" 
num_rounds: 4 
num_clients: 12 
batch_size: 1024 
num_classes: 2 
num_clients_per_round_fit: 3 
num_clients_per_round_eval: 5 
config_fit: 
  lr: 0.001 
  momentum: 0.9 
  local_epochs: 1 
